version: '25.0.3'

services:
  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/exam_portal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nikola07
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: exam_portal
      MYSQL_ROOT_PASSWORD: Nikola07
      MYSQL_USER: root
      MYSQL_PASSWORD: Nikola07

  # React Frontend
  frontend:
    build:
      context: C:\Users\Nikola Knezevic\Desktop\Projects\React\exam-portal
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
